
name: Draw Lottery Winner

on:
  schedule:
    - cron: "0 0 * * *"  # Once a day at midnight UTC
  workflow_dispatch:      # Manual trigger

jobs:
  draw-winner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Winner Draw Script
        run: python scripts/pick_winner.py

      - name: Commit and Push Winner Update
        run: |
          git config --global user.name "blockman-ai"
          git config --global user.email "bot@blockman.ai"
          git add data/winners_history.json data/lottery_entries.json data/lottery_status.json

          if ! git diff --cached --quiet; then
            git commit -m "Daily draw winner update"
            git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
          else
            echo "No winner update to commit."
